name: TreeOctopus
version: 1.1
author: insanj
main: me.insanj.TreeOctopus.TreeOctopus
description: When a user places a gold block on a leaf, or left clicks it, the sacrifice to the sacred TreeOctopus is accepted.
website: http://forums.bukkit.org/threads/the-pacific-northwest-tree-octopus.29301/

commands:
  octopus:
    #Use the following permission as a substitute for this command.
    permissions: replicator.disable
    description: Disables the plugin, because it is enabled by default.
    usage: /<command>